### ISSUE TITLE
Could I fork it under GNU GPLv3 (or any later)?

### ISSUE THREAD

**Issue by ghost** [limbahq/binreloc#3]
Please, explain me how should use your code in transition `WTFPL --> GNU GPLv3` (or `WTFPL --> BSD`, etc)
* https://softwareengineering.stackexchange.com/questions/205565/can-i-wtfpl-cc0-parts-of-a-gpl-code

P.S.: I want bundle `binreloc` into next software package
* https://github.com/Symbian9/azpainter/issues/15

**Comment by ximion** [comment]
You can relicense the WTFPL code to GPLv3 or BSD - this license was explicitly chosen so you would be able to do that and there are zero obstacles to embedding it into your own codebase.
The Binreloc code is essentially an example snippet, meant to be added to other projects.

So, tl;dr: Go ahead!
